is_father(abda,adonirao).
is_father(abdeel,selemias).
is_father(abdiel,ai).
is_father(abdi,quis).
is_father(abiail,zuriel).
is_father(abias,asafe).
is_father(abiatar,abimeleque).
is_father(abiel,quis).
is_father(abital,sefatias).
is_father(abiude,eliaquim).
is_father(abner,jaasiel).
is_father(abraao,davi).
is_father(acasbai,elifelete).
is_father(acbor,rana).
is_father(ada,elifaz).
is_father(adaias,maaseias).
is_father(adiel,azmavete).
is_father(adiel,maasai).
is_father(adlai,safate).
is_father(age,sama).
is_father(ailude,baana).
is_father(aimeleque,abiatar).
is_father(aitofel,elia).
is_father(aitube,aija).
is_father(aitube,ouve).
is_father(aitube,zadoque).
is_father(aiuube,zadoque).
is_father(alai,zabade).
is_father(alfeu,levi).
is_father(altube,meraiote).
is_father(amarias,gedalias).
is_father(amazias,azarias).
is_father(amazias,hasabias).
is_father(amazias,josa).
is_father(amisadai,aizer).
is_father(amitai,jonas).
is_father(amiude,principe_pedael).
is_father(amiude,semuel).
is_father(amiude,utai).
is_father(amiur,talmai).
is_father(ananias,maaseias).
is_father(anzi,pelalias).
is_father(aquim,eliude).
is_father(arao,aminadabe).
is_father(ara,secanias).
is_father(asa,berequias).
is_father(asael,jonatas).
is_father(asafe,josafa).
is_father(asafe,zabdi).
is_father(asafe,zicri).
is_father(asa,jeosafa).
is_father(asiel,seraias).
is_father(assir,taate).
is_father(assuero,dario).
is_father(atalias,jesaias).
is_father(azanias,jesua).
is_father(aza,principe_paltiel).
is_father(azarel,amassai).
is_father(azarias,amarias).
is_father(azarias,joel).
is_father(azaz,bela).
is_father(azazias,oseias).
is_father(azbuque,neemias).
is_father(azor,sadoque).
is_father(azriel,seraias).
is_father(azrriel,jerimote).
is_father(azur,hananias).
is_father(azur,jaazanias).
is_father(baana,helebe).
is_father(baana,helede).
is_father(baana,zadoque).
is_father(baasa,ela).
is_father(baaseias,micael).
is_father(bani,anzi).
is_father(bani,reum).
is_father(bani,uzi).
is_father(baraquias,zacarias).
is_father(bari,inri).
is_father(baruque,maaseias).
is_father(barzilai,adriel).
is_father(basemate,reuel).
is_father(becorate,zeror).
is_father(beeri,oseias).
is_father(benaias,jeoiada).
is_father(beor,bela).
is_father(berequias,asafe).
is_father(besodeias,mesulao).
is_father(betuel,labao).
is_father(binui,noadias).
is_father(booz,rute).
is_father(buzi,ezequiel).
is_father(buz,jado).
is_father(cadmiel,jesua).
is_father(cis,saul).
is_father(coate,izar).
is_father(colaias,acabe).
is_father(col,salum).
is_father(core,meselemias).
is_father(core,salum).
is_father(cuche,filho_selemias).
is_father(cuche,sofonias).
is_father(cusaias,eta).
is_father(davi,absalao).
is_father(davi,amnom).
is_father(davi,jerimote).
is_father(davi,jesus_cristo).
is_father(davi,jose).
is_father(delaias,semaias).
is_father(dodavau,eliezer).
is_father(ebzai,naarai).
is_father(efode,principe_haniel).
is_father(ela,simei).
is_father(elcana,zufe).
is_father(eleazar,mata).
is_father(eliada,rezom).
is_father(eliaquim,azor).
is_father(eliasibe,joana).
is_father(eli,jose).
is_father(elisama,netanias).
is_father(eliude,eleazar).
is_father(enoque,irade).
is_father(esau,elifaz).
is_father(esau,reuel).
is_father(esrom,arao).
is_father(fares,esrom).
is_father(fineias,abisua).
is_father(fineias,eleazar).
is_father(fineias,icabo).
is_father(gemali,amiel).
is_father(gemarias,micaias).
is_father(gera,eude).
is_father(gersom,jonatas).
is_father(gersom,sebuel).
is_father(gerson,jaate).
is_father(gileade,hefer).
is_father(gileade,jaroa).
is_father(hacalias,palavras_de_neemias).
is_father(hacmoni,jeiel).
is_father(hadlai,amasa).
is_father(hagedolim,zabdiel).
is_father(haloes,salum).
is_father(hamor,siquem).
is_father(hananias,zedequias).
is_father(haraias,uziel).
is_father(harim,malquias).
is_father(harri,mibar).
is_father(harum,acarel).
is_father(harumafe,jedaias).
is_father(hasabneias,hatus).
is_father(hasai,baana).
is_father(hassenua,hodavias).
is_father(hazaias,hoze).
is_father(henadade,bavai).
is_father(henadade,binui).
is_father(hezrom,calebe).
is_father(hilel,abdom).
is_father(hilel,israel_abdom).
is_father(hilquias,gemarias).
is_father(hilquias,jeremias).
is_father(hilquias,seraias).
is_father(hori,safate).
is_father(hosaias,azarias).
is_father(hosaias,jezanias).
is_father(hur,calebe).
is_father(huri,abiail).
is_father(hur,refaias).
is_father(ibnijas,reuel).
is_father(ido,ainadabe).
is_father(imer,mesilemite).
is_father(imer,pasur).
is_father(imer,zadoque).
is_father(imna,core).
is_father(inri,onri).
is_father(isaque,jaco).
is_father(ismael,zebadias).
is_father(israel,levi).
is_father(izar,cora).
is_father(jaare,hana).
is_father(jaco,jose).
is_father(jaco,juda).
is_father(jair,hana).
is_father(jair,mordecai).
is_father(jaque_de_massa,palavras_de_agur).
is_father(jealelel,azurias).
is_father(jeberequias,zacarias).
is_father(jedaias,alom).
is_father(jefone,calebe).
is_father(jeiel,benaias).
is_father(jeiel,obadias).
is_father(jeiel,seeanias).
is_father(jeoana,ismael).
is_father(jeoas,jeroboao).
is_father(jeremias,jaazanias).
is_father(jeroao,azarel).
is_father(jeroao,azarias).
is_father(jeroao,ibneias).
is_father(jeroboao,abias).
is_father(jeroboao,nadabe).
is_father(jeroboao,zacarias).
is_father(jerubaal,abimeleque).
is_father(jerubaal,jotao).
is_father(jerubesete,abimeleque).
is_father(jesaias,itiel).
is_father(jesisai,micael).
is_father(jesse,eliabe).
is_father(jesua,ezer).
is_father(jesua,joiaquim).
is_father(jesua,jozabade).
is_father(jeu,jeoacaz).
is_father(jigdalias,hana).
is_father(joacaz,joa).
is_father(joana,azarias).
is_father(joas,jerubaal).
is_father(joatao,acaz).
is_father(joel,elcana).
is_father(joel,hema).
is_father(joel,sema).
is_father(jogli,principe_buqui).
is_father(joiaribe,adaias).
is_father(joiaribe,jedaias).
is_father(jonatas,ebede).
is_father(jonata,zacarias).
is_father(josafa,jorao).
is_father(jose,ioal).
is_father(jose,jesus_de_nazare).
is_father(josias,eliaquim).
is_father(josias,jeconias).
is_father(josias,salum).
is_father(josibias,jeu).
is_father(juda,fares).
is_father(juda,perez).
is_father(juda,sela).
is_father(juda,tamar).
is_father(juda,zara).
is_father(juda,zera).
is_father(lael,eliasafe).
is_father(lais,palti).
is_father(lais,paltiel).
is_father(levi,gerson).
is_father(levi,mali).
is_father(levi,merari).
is_father(maaca,abias).
is_father(maaca,aquis).
is_father(maaca,hana).
is_father(maaca,sefatias).
is_father(maalelel,sefatias).
is_father(maaseias,azarias).
is_father(maaseias,colaias).
is_father(maaseias,zedequias).
is_father(maluque,abdi).
is_father(manasses,amom).
is_father(maoque,aquis).
is_father(maqui,geuel).
is_father(mata,jaco).
is_father(matanias,hasabias).
is_father(matanias,semaias).
is_father(mata,sefatias).
is_father(menaem,pecaias).
is_father(meselemias,zacarias).
is_father(mesezabel,petaias).
is_father(mesilemote,aazai).
is_father(mesilemote,berequias).
is_father(mesulao,jazera).
is_father(mica,abdom).
is_father(micael,onri).
is_father(micael,setur).
is_father(micael,zebadias).
is_father(micaias,acbor).
is_father(musi,mali).
is_father(naas,sobi).
is_father(naor,filha_de_betuel).
is_father(naor,labao).
is_father(nasom,salmom).
is_father(nata,azarias).
is_father(nata,igal).
is_father(nata,zabude).
is_father(nebate,rei_jeroboao).
is_father(nerias,seraias).
is_father(netanel,semaias).
is_father(netanias,jeudi).
is_father(obadias,ismaias).
is_father(obede,azarias).
is_father(obede,jesse).
is_father(odede,azarias).
is_father(ozias,joatao).
is_father(paate,hassube).
is_father(parnaque,principe_elizafa).
is_father(paros,pedaias).
is_father(parua,jeosafa).
is_father(paseia,joiada).
is_father(pasur,gedalias).
is_father(pedaias,joede).
is_father(pedaias,joel).
is_father(pelete,om).
is_father(petuel,joel).
is_father(pirro,sopater_de_bereia).
is_father(puva,tola).
is_father(quelube,ezri).
is_father(quemuel,hasabias).
is_father(quisi,eta).
is_father(quislom,elida).
is_father(quis,simei).
is_father(rafu,palti).
is_father(recabe,malquias).
is_father(remalia,peca).
is_father(reuel,eliasafe).
is_father(reuel,hobabe).
is_father(roboao,abias).
is_father(ruben,eliabe).
is_father(sacar,aiao).
is_father(sadoque,aquim).
is_father(safa,elasa).
is_father(safa,gemarias).
is_father(safa,jaazanias).
is_father(safate_de_abel,eliseu).
is_father(sage,jonatas).
is_father(salatiel,zorobabel).
is_father(salmom,raabe).
is_father(salum,hanamel).
is_father(salum,jeizquias).
is_father(salu,zinri).
is_father(samua,abda).
is_father(samuel,joel).
is_father(sarar,aiao).
is_father(saul,mefibosete).
is_father(sealtiel,juda).
is_father(sealtiel,juda_zorobabel).
is_father(secanias,semaias).
is_father(sefatias,mesulao).
is_father(selemias,hananias).
is_father(selemias,jeucal).
is_father(selemias,jurias).
is_father(selomi,principe_aiude).
is_father(semaias,delaias).
is_father(semaias,obadias).
is_father(semaias,sinri).
is_father(semaias,urias).
is_father(senua,juda).
is_father(seraias,esdras).
is_father(sifi,ziza).
is_father(sifta,principe_quemuel).
is_father(simeate,jozacar).
is_father(simeate,zabade).
is_father(simeia,berequias).
is_father(simeia,jonatas).
is_father(simei,jonatas).
is_father(sinri,jediael).
is_father(sinrite,jeozabade).
is_father(siza,adina).
is_father(sobal,reaias).
is_father(sodi,gadiel).
is_father(sofonias,azarias).
is_father(sofonias,hem).
is_father(sofonias,josias).
is_father(somer,jeozabade).
is_father(susi,gadi).
is_father(tabrimom,hadade).
is_father(ticva,salum).
is_father(toa,eliel).
is_father(tocate,salum).
is_father(tou,eliu).
is_father(ur,elifal).
is_father(uri,bezaleel).
is_father(uri,geber).
is_father(uzai,palal).
is_father(uzias,ataias).
is_father(uzias,jonatas).
is_father(uzi,ela).
is_father(uziel,elizafa).
is_father(uzi,zeraias).
is_father(vofsi,nabi).
is_father(zabai,baruque).
is_father(zabdiel,jasobeao).
is_father(zacarias,anzi).
is_father(zacarias,jaaziel).
is_father(zacarias,joao).
is_father(zacarias,joiaribe).
is_father(zacarias,uzias).
is_father(zacur,hana).
is_father(zacur,micaias).
is_father(zacur,samua).
is_father(zadoque,azarias).
is_father(zadoque,salum).
is_father(zeniia,joabe).
is_father(zera_de_bozra,jobabe).
is_father(zera,etni).
is_father(zeraias,elioenai).
is_father(zera,jobabe).
is_father(zicri,amasias).
is_father(zicri,chefe_eliezer).
is_father(zicri,elisafate).
is_father(zicri,joel).
is_father(zima,eta).
is_father(zima,joa).
is_father(zorobabel,abiude).
is_married(jose,maria).
is_pessoa(aazai).
is_pessoa(abdeel).
is_pessoa(abdiel).
is_pessoa(abiel).
is_pessoa(abisua).
is_pessoa(abital).
is_pessoa(acarel).
is_pessoa(acasbai).
is_pessoa(ada).
is_pessoa(adina).
is_pessoa(adlai).
is_pessoa(adonirao).
is_pessoa(adriel).
is_pessoa(age).
is_pessoa(ai).
is_pessoa(aija).
is_pessoa(ainadabe).
is_pessoa(aitofel).
is_pessoa(aiuube).
is_pessoa(aizer).
is_pessoa(alai).
is_pessoa(alom).
is_pessoa(altube).
is_pessoa(amasias).
is_pessoa(amassai).
is_pessoa(amitai).
is_pessoa(amiur).
is_pessoa(amnom).
is_pessoa(ananias).
is_pessoa(aquis).
is_pessoa(aquis).
is_pessoa(ara).
is_pessoa(asael).
is_pessoa(asiel).
is_pessoa(assir).
is_pessoa(assuero).
is_pessoa(ataias).
is_pessoa(atalias).
is_pessoa(aza).
is_pessoa(azanias).
is_pessoa(azaz).
is_pessoa(azazias).
is_pessoa(azbuque).
is_pessoa(azmavete).
is_pessoa(azriel).
is_pessoa(azrriel).
is_pessoa(azurias).
is_pessoa(baaseias).
is_pessoa(baraquias).
is_pessoa(bari).
is_pessoa(barzilai).
is_pessoa(basemate).
is_pessoa(bavai).
is_pessoa(becorate).
is_pessoa(beeri).
is_pessoa(besodeias).
is_pessoa(bezaleel).
is_pessoa(booz).
is_pessoa(buz).
is_pessoa(buzi).
is_pessoa(cadmiel).
is_pessoa(chefe_eliezer).
is_pessoa(cis).
is_pessoa(col).
is_pessoa(cusaias).
is_pessoa(dario).
is_pessoa(dodavau).
is_pessoa(ebzai).
is_pessoa(efode).
is_pessoa(elasa).
is_pessoa(eli).
is_pessoa(elia).
is_pessoa(eliada).
is_pessoa(eliasibe).
is_pessoa(elida).
is_pessoa(eliel).
is_pessoa(eliezer).
is_pessoa(elifal).
is_pessoa(elifelete).
is_pessoa(elioenai).
is_pessoa(elisafate).
is_pessoa(elizafa).
is_pessoa(enoque).
is_pessoa(esdras).
is_pessoa(etni).
is_pessoa(eude).
is_pessoa(ezequiel).
is_pessoa(ezer).
is_pessoa(ezri).
is_pessoa(filha_de_betuel).
is_pessoa(filho_selemias).
is_pessoa(gadiel).
is_pessoa(geber).
is_pessoa(gemali).
is_pessoa(geuel).
is_pessoa(hacalias).
is_pessoa(hacmoni).
is_pessoa(hadlai).
is_pessoa(hagedolim).
is_pessoa(haloes).
is_pessoa(hamor).
is_pessoa(hanamel).
is_pessoa(haraias).
is_pessoa(harim).
is_pessoa(harri).
is_pessoa(harum).
is_pessoa(harumafe).
is_pessoa(hasabneias).
is_pessoa(hasai).
is_pessoa(hassenua).
is_pessoa(hatus).
is_pessoa(hazaias).
is_pessoa(helebe).
is_pessoa(helede).
is_pessoa(hem).
is_pessoa(hema).
is_pessoa(hezrom).
is_pessoa(hobabe).
is_pessoa(hodavias).
is_pessoa(hori).
is_pessoa(hoze).
is_pessoa(huri).
is_pessoa(ibneias).
is_pessoa(ibnijas).
is_pessoa(icabo).
is_pessoa(igal).
is_pessoa(imna).
is_pessoa(ioal).
is_pessoa(irade).
is_pessoa(ismaias).
is_pessoa(israel_abdom).
is_pessoa(itiel).
is_pessoa(jaare).
is_pessoa(jaasiel).
is_pessoa(jaate).
is_pessoa(jaaziel).
is_pessoa(jado).
is_pessoa(jaque_de_massa).
is_pessoa(jaroa).
is_pessoa(jasobeao).
is_pessoa(jazera).
is_pessoa(jealelel).
is_pessoa(jeberequias).
is_pessoa(jediael).
is_pessoa(jefone).
is_pessoa(jeizquias).
is_pessoa(jeoana).
is_pessoa(jerubesete).
is_pessoa(jesisai).
is_pessoa(jesus_cristo).
is_pessoa(jesus_de_nazare).
is_pessoa(jeucal).
is_pessoa(jeudi).
is_pessoa(jezanias).
is_pessoa(jigdalias).
is_pessoa(joacaz).
is_pessoa(joede).
is_pessoa(jogli).
is_pessoa(joiada).
is_pessoa(joiaquim).
is_pessoa(jonas).
is_pessoa(jonata).
is_pessoa(josa).
is_pessoa(josibias).
is_pessoa(jozabade).
is_pessoa(jozacar).
is_pessoa(juda_zorobabel).
is_pessoa(jurias).
is_pessoa(lael).
is_pessoa(maalelel).
is_pessoa(maasai).
is_pessoa(maluque).
is_pessoa(maoque).
is_pessoa(maqui).
is_pessoa(maria).
is_pessoa(meraiote).
is_pessoa(merari).
is_pessoa(mesezabel).
is_pessoa(mesilemite).
is_pessoa(mibar).
is_pessoa(mordecai).
is_pessoa(musi).
is_pessoa(naarai).
is_pessoa(nabi).
is_pessoa(nadabe).
is_pessoa(neemias).
is_pessoa(noadias).
is_pessoa(odede).
is_pessoa(om).
is_pessoa(ouve).
is_pessoa(ozias).
is_pessoa(paate).
is_pessoa(palal).
is_pessoa(palavras_de_agur).
is_pessoa(palavras_de_neemias).
is_pessoa(paltiel).
is_pessoa(parnaque).
is_pessoa(paros).
is_pessoa(parua).
is_pessoa(paseia).
is_pessoa(pecaias).
is_pessoa(pelalias).
is_pessoa(pelete).
is_pessoa(perez).
is_pessoa(petaias).
is_pessoa(petuel).
is_pessoa(pirro).
is_pessoa(principe_aiude).
is_pessoa(principe_buqui).
is_pessoa(principe_elizafa).
is_pessoa(principe_haniel).
is_pessoa(principe_paltiel).
is_pessoa(principe_pedael).
is_pessoa(principe_quemuel).
is_pessoa(puva).
is_pessoa(quelube).
is_pessoa(quemuel).
is_pessoa(quisi).
is_pessoa(quislom).
is_pessoa(raabe).
is_pessoa(rafu).
is_pessoa(rana).
is_pessoa(reaias).
is_pessoa(refaias).
is_pessoa(rei_jeroboao).
is_pessoa(remalia).
is_pessoa(reum).
is_pessoa(rezom).
is_pessoa(rute).
is_pessoa(sacar).
is_pessoa(safate_de_abel).
is_pessoa(sage).
is_pessoa(salatiel).
is_pessoa(sama).
is_pessoa(samuel).
is_pessoa(sarar).
is_pessoa(sebuel).
is_pessoa(seeanias).
is_pessoa(sela).
is_pessoa(selomi).
is_pessoa(sema).
is_pessoa(semuel).
is_pessoa(senua).
is_pessoa(setur).
is_pessoa(sifi).
is_pessoa(sifta).
is_pessoa(sinrite).
is_pessoa(siquem).
is_pessoa(siza).
is_pessoa(sobal).
is_pessoa(sobi).
is_pessoa(sodi).
is_pessoa(somer).
is_pessoa(sopater_de_bereia).
is_pessoa(susi).
is_pessoa(taate).
is_pessoa(tabrimom).
is_pessoa(talmai).
is_pessoa(tamar).
is_pessoa(ticva).
is_pessoa(toa).
is_pessoa(tocate).
is_pessoa(tola).
is_pessoa(tou).
is_pessoa(ur).
is_pessoa(utai).
is_pessoa(uzai).
is_pessoa(vofsi).
is_pessoa(zabai).
is_pessoa(zabude).
is_pessoa(zara).
is_pessoa(zeniia).
is_pessoa(zera_de_bozra).
is_pessoa(zeror).
is_pessoa(zinri).
is_pessoa(ziza).
is_pessoa(zufe).
is_pessoa(zuriel).
