"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Abreviacoes.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/UnidadeOrganica.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/MesesNum.fst2" Merge Disabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Dias.fst2" Merge Disabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Horas.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Meses.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/palavrasMinusculasHarem.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Numero.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/NumRomanos.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Valor.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Datas_Def.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Data.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Tempo.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Preposicao.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Coisa.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/LocalSigarra.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Acontecimento.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Outro.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Obra.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Abstraccao.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Local.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Enumeracao.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Nao-Pessoa.fst2" Merge Disabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/1-ReconheceNomesCompostos.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/2-Reconhece2NomesProprios.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/11-ReconheceNomesLeNer.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/3-ReconheceAcoesHumAEsquerda.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/4-ReconhecePronomesDeTratamento.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/5-ReconheceAcoesHumADireita.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/6-ReconheceAposto.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/7-ReconheceMinusculasHAREMAEsquerda.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/8-ReconheceContextoAEsquerda.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/8-ReconhecePerguntasComNomes.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/9-AcaoRealizadaPor.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/10-ReconheceNomeSucedidoPorIdade.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Organizacao.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/12-ReconheceNomeSemContexto.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Enumeracao.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/Paralelismo.fst2" Merge Enabled 1 0
"../../../../../Documentos/TrabalhoElias/AnotaCDComLG/Grafos/13-ReconheceRelacoesPaternidade-Biblia.fst2" Merge Enabled 1 0
